on:
  push:
    branches:
      - develop

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: make application-db.properties
        run: |
          cd ./src/main/resources
          echo "spring.data.mongodb.uri=$MONGO_DB_URI" >> application-db.properties
          echo "spring.data.mongodb.database=$MONGO_DB_DATABASE" >> application-db.properties
        shell: bash
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          MONGO_DB_DATABASE: ${{ secrets.MONGO_DB_DATABASE }}

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://novel-palace-bucket/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name novel-palace --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=novel-palace-bucket,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

